---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(devtools)
library(mosaic)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
child_mortality_rate <- ourworldindata::child_mortality
child_mortality_rate2 <- filter(child_mortality_rate, year == "2010" )
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r}
child_mortality_rate3 <- filter(child_mortality_rate2, population >= 126535920) 


```

```{r}
child_mortality_rate3 %>% 
  arrange(country)
```

```{r}
child_mortality_rate3 %>% 
  summarise(aveMortlaity = mean(child_mort))
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
ggplot(child_mortality_rate3, aes(x=child_mort, y=deaths_per_woman)) +
  geom_point(size = 6, color = "red", pch = 18) +
  labs(title="Child mortality rate compared to deaths per woman of top 10 most populated countries in the world", 
       x = "child mortality rate", y="deaths per woman") +
  theme_bw()

```

## Conclusions
"The visual above shows average child mortality rate of top 10 countries in the world on the basis of population for every 50 years."