---
title: "Wealth and Life Expectancy (Gapminder)"
author: "Polisma Yadav"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(gapminder)
library(ggplot2)
```


## Background

Things learned while making the plot:
Europe has the highest GDP and life Expectancy and Lowest GDP per capita and Life Expectancy is of Africa.
Americas come second to Europe and majority of population is Asia lie under the bottom half of the plot

## Image

```{r tidy_data}
gapminder %>%
 filter(country != "Kuwait") %>%
ggplot(mapping = aes(x=lifeExp, y=gdpPercap)) + 
  geom_point(mapping = aes(x=lifeExp, y=gdpPercap, color=continent, size=pop/100000)) +
  facet_wrap(~ year, nrow=1) + 
  scale_y_continuous(trans = "sqrt") + 
  labs(x = "Life Expectancy", y="GDP per capita",color = "Continent", size = "Population (100k)")

```

```{r}
ggsave("image1.png", width = 15, units = "in")
```